// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV0QYVMr_BrT4mQYdlP8LR3J7aK4NsVxs',
    appId: '1:402629599020:web:7ba37a6faffacd6b545689',
    messagingSenderId: '402629599020',
    projectId: 'fluttertest-51350',
    authDomain: 'fluttertest-51350.firebaseapp.com',
    storageBucket: 'fluttertest-51350.appspot.com',
    measurementId: 'G-BGEZ3YNLV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD28rX0G2L3HEt4NIXuIz8z_VMH8-Z97bc',
    appId: '1:402629599020:android:f01d5ee1710823fa545689',
    messagingSenderId: '402629599020',
    projectId: 'fluttertest-51350',
    storageBucket: 'fluttertest-51350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC50aEv3pvSeXvUoB5-SF2AiBCeF6N0j54',
    appId: '1:402629599020:ios:6891b58edbea4aad545689',
    messagingSenderId: '402629599020',
    projectId: 'fluttertest-51350',
    storageBucket: 'fluttertest-51350.appspot.com',
    iosClientId: '402629599020-8ng1lnmkqhv1pk8ccio3g05viqupoc5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC50aEv3pvSeXvUoB5-SF2AiBCeF6N0j54',
    appId: '1:402629599020:ios:6891b58edbea4aad545689',
    messagingSenderId: '402629599020',
    projectId: 'fluttertest-51350',
    storageBucket: 'fluttertest-51350.appspot.com',
    iosClientId: '402629599020-8ng1lnmkqhv1pk8ccio3g05viqupoc5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest',
  );
}
